[package]
name = "interprocess-drop-panic"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
tokio = { version = "1.40.0", features = ["macros"] }
interprocess = { version = "2.2.1", features = ["tokio"] }